### PR TITLE
Changed default conference page to conference list and integrated permissions with conference management page

### PR DESCRIPTION
**Pull request by movingpylon**

### CODE REVIEW

**Comment by nikkimartin** [comment]
A few things:
* Make the "Conferences" heading a bit bigger
* Add icon to create conference button
* Swap colours for register and view event buttons (register should be primary and view should be info)
* Do I need to put a photo upload thing in the conference creation?
* Does this PR include conference registration?

**Comment by nikkimartin** [comment]
also, I think the create conference button is visible for users who shouldn't be able to see it

**Comment by nikkimartin** [comment]
sorry, couple more things:
on the manage page
* change 'user registration' to say 'attendees' - I think the former could be confused with account creation audits
* get rid of the events row and just add 'edit events' to the top section (don't need view events - should be able to view them all on edit page)
* change 'edit' row to be 'create/edit'
* colour choices don't really seem to have any logic to them. match them either by category (e.g. all inventory related stuff is red) or action (e.g. all auditing is red)

I might still want to make a few more changes after this, but let's just see how these look first.

**Comment by movingpylon** [comment]
Made the visual changes. I don't know exactly how you want it to look, but you can change it to your liking. This does not include conference registration, it is just for the manage page. As for the photo upload, I was just thinking we could leave it as a stock photo for now.

**Comment by nikkimartin** [comment]
sounds good. go for it.

**Pull request merged**
