### PR TITLE
Permissions and user approval

### PR DESCRIPTION
**Pull request by movingpylon**
- Buttons will be hidden on conference management page if user does not have permission
- same for sidebar
- access to URLs will be restricted if user does not have permission
- user dependent approval
- assign permissions

### CODE REVIEW

**Comment by nikkimartin** [comment]
Mentioned some of this in slack but copying here for completeness:

- i said to change the word 'select' to not indicate a dropdown, but i actually think a dropdown would be better. having a dropdown w/ something like "<firstname> <lastname>: <email>" would be even better if feasible.
- specify to input email for role assignment if not switching to dropdown
- no indication that role assignment has worked (modal and/or redirect would be good)
- try to switch role dropdown to do something like roles.display_name (roles.description) - can use names you have if display name is null
- is the approve account tab for approving individual users? If so, I'd update the sidebar link to say users.
- we should maybe include a reject button that deletes the entries from the db. same w/ other auditing pages.

**Comment by nikkimartin** [comment]
also hide the register button for conferences if the user isn't approved

**Comment by nikkimartin** [comment]
sorry, last thing. probably actually for @brandonson.
I noticed that if i assign the owner permission to a new user i created, i can't manage conferences that i didn't create under that account. is this correct, or should it encompass ALL permissions?

**Comment by movingpylon** [comment]
- there is currently no endpoint for this
- fixed, wording might be a bit off though
- fixed with modal
- the endpoint does not return description. I suspect this would be a pretty easy fix. Will update once the endpoint is updated
- fixed
- there is no endpoint for reject atm

**Comment by nikkimartin** [comment]
- it still doesn't specify to use an email
- I would also try and hide the section labels in the management page if they don't have any permissions in that category.

**Comment by movingpylon** [comment]
- Button added for checking email/retrieving permissions
- It now indicates when permissions have changed when adding/removing permissions for a user
- Manage conference section labels are removed when there are no permissions for any widgets in that section

**Pull request merged**
