### PR TITLE
Conference Registration

### PR DESCRIPTION
**Pull request by brandonson**
This supports a fair amount of conference registration.

Currently no inventory handling etc, also needs better auth (there is none right now) for approval of registration request.

### CODE REVIEW

**Comment by XennMaestro** [comment]
last i remember alex was working with the Users table. Since you are changing the naming convention, did you double check with alex if it would break his current methods.

**Comment by XennMaestro** [comment]
does Flights have its own controller?Or are you implementing flights as a part of the conference registration controller?

**Comment by brandonson** [comment]
For the Users table, I believe that all got moved to the accounts table already.

For flights, we might end up having a related controller at some point, but the flight data we're keeping is all related to conference registration, so for now it all happens there.

Controllers should be more related to user activity than what DB tables they end up working with, IMO.

**Comment by XennMaestro** [comment]
Alright that's fine. 
You should include a short description at the top of the file. 
Since the file is quite large and has many different functions it can be difficult to read through every method to understand what functions the controller is performing.
A small bullet point list could help.

**Comment by brandonson** [comment]
List of things changed (per request on slack).

DB stuff:
* Added new Eloquent models for User, UserConference, and Flight
* Removed old User model (already replaced with Account)
* Updated DB to snake_case table names
* Added flags for Flight and UserConference to indicate whether they've been audited
* Added seeder for User
* Updated autoload_classmap.php to deal with DB renames

Controller/Tests:
* Added ConfRegistrationController (deals with conference registration)
 * Three routes: 
  * Initial registration request
  * Request data fetching
  * Request approval
 * Does a lot of logic for checking request validity
* Added ConferenceRegistrationTest to test the new behaviour
* Added 'idarray' to the Validator to check ID array validity
* Added TokenTestCase to deal with tests that need to handle tokens
 * Gets a token every time a test is set up
 * Overrides 'json' and 'call' to send headers with the token

I'll go through and add comments to ConferenceRegistrationController and TokenTestCase at some point before merging.

**Comment by brandonson** [comment]
@XennMaestro Let me know if it looks good now, I think I made things at least a bit clearer.

**Comment by nikkimartin** [comment]
okay from me!

**Pull request merged**
